"""Portuguese messages for errors generated by the API framework."""

import logging

from fastapi import Request
from fastapi.exception_handlers import http_exception_handler, request_validation_exception_handler
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse, Response
from starlette.exceptions import HTTPException

logger = logging.getLogger(__name__)

HTTP_MESSAGES = {
    "Not authenticated": "É necessário entrar na sua conta para continuar.",
    "Invalid authentication credentials": "As credenciais de autenticação são inválidas.",
    "Not Found": "Recurso não encontrado.",
    "Method Not Allowed": "Esta operação não é permitida.",
    "Bad Request": "A solicitação é inválida.",
    "Unauthorized": "É necessário entrar na sua conta para continuar.",
    "Forbidden": "Você não tem permissão para realizar esta operação.",
    "Internal Server Error": "Ocorreu um erro interno. Tente novamente mais tarde.",
    "There was an error parsing the body": "Não foi possível interpretar os dados enviados.",
}

VALIDATION_MESSAGES = {
    "missing": "Este campo é obrigatório.",
    "string_type": "Informe um texto válido.",
    "string_too_short": "Informe pelo menos {min_length} caractere(s).",
    "string_too_long": "Informe no máximo {max_length} caractere(s).",
    "string_pattern_mismatch": "O formato informado é inválido.",
    "greater_than_equal": "Informe um valor maior ou igual a {ge}.",
    "decimal_parsing": "Informe um número válido.",
    "decimal_type": "Informe um número válido.",
    "finite_number": "Informe um número finito.",
    "bool_parsing": "Informe um valor verdadeiro ou falso.",
    "bool_type": "Informe um valor verdadeiro ou falso.",
    "uuid_parsing": "O identificador informado é inválido.",
    "uuid_type": "O identificador informado é inválido.",
    "date_from_datetime_parsing": "Informe uma data válida no formato AAAA-MM-DD.",
    "date_from_datetime_inexact": "Informe uma data sem horário no formato AAAA-MM-DD.",
    "date_parsing": "Informe uma data válida no formato AAAA-MM-DD.",
    "date_type": "Informe uma data válida no formato AAAA-MM-DD.",
    "json_invalid": "Os dados enviados não estão em um formato JSON válido.",
    "model_attributes_type": "Envie os campos em um objeto JSON válido.",
}


async def localized_http_error(request: Request, exc: Exception) -> Response:
    assert isinstance(exc, HTTPException)
    if isinstance(exc.detail, str):
        exc.detail = HTTP_MESSAGES.get(exc.detail, exc.detail)
    return await http_exception_handler(request, exc)


async def localized_validation_error(request: Request, exc: Exception) -> Response:
    assert isinstance(exc, RequestValidationError)
    for error in exc.errors():
        if error["type"] == "value_error" and error.get("loc", ())[-1:] in (
            ("email",), ("guest_email",),
        ):
            error["msg"] = "Informe um endereço de e-mail válido."
        else:
            template = VALIDATION_MESSAGES.get(error["type"], "O valor informado é inválido.")
            error["msg"] = template.format(**error.get("ctx", {}))
    return await request_validation_exception_handler(request, exc)


async def localized_internal_error(request: Request, exc: Exception) -> JSONResponse:
    logger.error("Unhandled API error", exc_info=exc)
    return JSONResponse(
        status_code=500,
        content={"detail": HTTP_MESSAGES["Internal Server Error"]},
    )
